sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nag23101990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nag23101990/docker-react npm run test