sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nag23101990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nag23101990/docker-react npm run test

deploy: 
  edge: true
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk:eu-west-1:242610718642'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY